development:
  adapter: postgresql
  encoding: unicode
  database: yaledancers_development
  pool: 5
  username: yaledancers
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: yaledancers_test
  pool: 5
  username: yaledancers
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: yaledancers_production
  pool: 5
  username: yaledancers
  password:
